/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/scenes/building_1/Building_1.glb --output src/Components/Buildings/Building_1.js 
*/

import React from 'react';
import { useGLTF } from '@react-three/drei';
import * as THREE from 'three';

export function Building_1(props) {
  const { nodes, materials } = useGLTF('/models/scenes/building_1/Building_1.glb');
  materials['glass.006'] = new THREE.MeshPhysicalMaterial({
    color: new THREE.Color('#f0f0f0'), //Light gray tint to avoid pure white; try #e0f0ff for blueish glass
    transmission: 0.95, //Slightly less than 1 for realism (full 1 can wash out)
    opacity: 0.8,
    roughness: 0.05, //Low for smooth reflections
    metalness: 0,
    ior: 1.52,
    thickness: 0.2, //Thickness for refraction depth (adjust based on model scale; too low = no distortion)
    envMapIntensity: 1.2,
    transparent: true,
  })
  /*
   materials['Mirror'] = new THREE.MeshPhysicalMaterial({ // Assuming your material name
    color: new THREE.Color('#111111'),
    metalness: 1.0,
    roughness: 0.0,
    envMapIntensity: 1.5, // Boost to make reflections pop
    clearcoat: 1.0, // Optional: Adds a glossy layer for realism
    clearcoatRoughness: 0.0,
  });
   */
  return (
    <group {...props} dispose={null}>
      <group position={[-30.935, 0, 7.429]}>
        <mesh geometry={nodes.Business_Centre001.geometry} material={materials._White} />
        <mesh geometry={nodes.Business_Centre002.geometry} material={materials._Black} />
        <mesh geometry={nodes.Business_Centre003.geometry} material={materials._Black} />
        <mesh geometry={nodes.Business_Centre004.geometry} material={materials._Black} />
        <mesh geometry={nodes.Business_Centre005.geometry} material={materials._Black} />
        <mesh geometry={nodes.Business_Centre006.geometry} material={materials._Black} />
        <mesh geometry={nodes.Business_Centre007.geometry} material={materials._Black} scale={[1, 0.822, 1]} />
        <mesh geometry={nodes.Business_Centre008.geometry} material={materials._Black} />
        <mesh geometry={nodes.Business_Centre009.geometry} material={materials._Black} />
        <mesh geometry={nodes.Business_Centre010.geometry} material={materials._Black} />
        <mesh geometry={nodes.Business_Centre011.geometry} material={materials._White} />
        <mesh geometry={nodes.Business_Centre012.geometry} material={materials['glass.006']} />
        <mesh geometry={nodes.Business_Centre013.geometry} material={materials._White} />
        <mesh geometry={nodes.Business_Centre019.geometry} material={materials._White} />
        <mesh geometry={nodes.Business_Centre020.geometry} material={materials._Black} />
        <mesh geometry={nodes.Business_Centre021.geometry} material={materials._White} />
        <mesh geometry={nodes.Business_Centre022.geometry} material={materials._Black} />
        <mesh geometry={nodes.Business_Centre023.geometry} material={materials._Black} />
        <mesh geometry={nodes.Business_Centre024.geometry} material={materials._White} />
        <mesh geometry={nodes.Business_Centre025.geometry} material={materials.StoneTile} />
        <mesh geometry={nodes.Business_Centre027.geometry} material={materials._Black} />
        <mesh geometry={nodes.Business_Centre028.geometry} material={materials._Black} />
        <mesh geometry={nodes.Business_Centre029.geometry} material={materials.aluminum2} />
        <mesh geometry={nodes.Business_Centre030.geometry} material={materials._Black} />
        <mesh geometry={nodes.Business_Centre031.geometry} material={materials._Black} />
        <mesh geometry={nodes.Business_Centre032.geometry} material={materials._White} />
        <mesh geometry={nodes.Business_Centre033.geometry} material={materials._Black} />
        <mesh geometry={nodes.Business_Centre034.geometry} material={materials._Black} />
        <mesh geometry={nodes.Business_Centre035.geometry} material={materials._White} />
        <mesh geometry={nodes.Mesh003.geometry} material={materials.aluminum2} />
        <mesh geometry={nodes.Mesh003_1.geometry} material={materials['glass.006']} />
        <mesh geometry={nodes.Mesh094.geometry} material={materials.aluminum2} />
        <mesh geometry={nodes.Mesh094_1.geometry} material={materials['glass.006']} />
        <mesh geometry={nodes.Mesh095.geometry} material={materials.aluminum2} />
        <mesh geometry={nodes.Mesh095_1.geometry} material={materials['glass.006']} />
        <mesh geometry={nodes.Mesh096.geometry} material={materials.aluminum2} />
        <mesh geometry={nodes.Mesh096_1.geometry} material={materials['glass.006']} />
        <mesh geometry={nodes.Mesh097.geometry} material={materials.aluminum2} />
        <mesh geometry={nodes.Mesh097_1.geometry} material={materials['glass.006']} />
        <mesh geometry={nodes.Mesh098.geometry} material={materials._Black} />
        <mesh geometry={nodes.Mesh098_1.geometry} material={materials._Black} />
        <mesh geometry={nodes.Mesh098_2.geometry} material={materials['glass.006']} />
        <mesh geometry={nodes.Mesh098_3.geometry} material={materials._Black} />
      </group>
      <group position={[29.735, 0.2, -4.927]}>
        <mesh geometry={nodes.Clay.geometry} material={materials.BrownClay} />
        <mesh geometry={nodes.PlantMonstera.geometry} material={materials.Plant} />
        <mesh geometry={nodes.Vase.geometry} material={materials['Clay Gray']} />
      </group>
      <group position={[8.711, 0.2, -9.031]} rotation={[0, 1.571, 0]}>
        <mesh geometry={nodes.Clay001.geometry} material={materials.BrownClay} />
        <mesh geometry={nodes.PlantMonstera001.geometry} material={materials.Plant} />
        <mesh geometry={nodes.Vase001.geometry} material={materials['Clay Gray']} />
      </group>
      <group position={[-23.565, 0.2, 5.765]} rotation={[0, 1.571, 0]}>
        <mesh geometry={nodes.Clay002.geometry} material={materials.BrownClay} />
        <mesh geometry={nodes.PlantMonstera002.geometry} material={materials.Plant} />
        <mesh geometry={nodes.Vase002.geometry} material={materials['Clay Gray']} />
      </group>
      <group position={[-21.527, 0.2, -9.087]}>
        <mesh geometry={nodes.Clay003.geometry} material={materials.BrownClay} />
        <mesh geometry={nodes.PlantMonstera003.geometry} material={materials.Plant} />
        <mesh geometry={nodes.Vase003.geometry} material={materials['Clay Gray']} />
      </group>
      <group position={[10.263, 0.2, -6.024]} rotation={[Math.PI, 0, Math.PI]}>
        <mesh geometry={nodes.back.geometry} material={materials.fabric} position={[0, 0.346, -0.337]} rotation={[0, 1.571, 0]} />
        <mesh geometry={nodes.Back_cousion.geometry} material={materials.fabric} position={[-0.602, 0.566, -0.233]} rotation={[-0.244, 0, 0]} />
        <mesh geometry={nodes.Back_cousion001.geometry} material={materials.fabric} position={[0.599, 0.566, -0.233]} rotation={[-0.244, 0, 0]} />
        <mesh geometry={nodes.Back_cousion002.geometry} material={materials.fabric} position={[0, 0.566, -0.233]} rotation={[-0.244, 0, 0]} />
        <mesh geometry={nodes.bottom.geometry} material={materials.fabric} position={[0, 0.152, 0.036]} />
        <mesh geometry={nodes.legs.geometry} material={materials.metal} position={[0, 0.024, 0]} />
        <mesh geometry={nodes.pillow001.geometry} material={materials['pillow black']} position={[0.756, 0.539, -0.031]} rotation={[-0.334, -0.463, -0.154]} />
        <mesh geometry={nodes.pillow002.geometry} material={materials['pillow brown']} position={[0.498, 0.558, -0.03]} rotation={[-0.335, -0.338, -0.116]} />
        <mesh geometry={nodes.pillow003.geometry} material={materials['pillow black']} position={[-0.762, 0.539, -0.037]} rotation={[2.793, -0.453, -0.186]} scale={-1} />
        <mesh geometry={nodes.seat_cousion.geometry} material={materials.fabric} position={[0.597, 0.304, 0.109]} />
        <mesh geometry={nodes.seat_cousion001.geometry} material={materials.fabric} position={[0, 0.304, 0.109]} />
        <mesh geometry={nodes.seat_cousion002.geometry} material={materials.fabric} position={[-0.599, 0.304, 0.109]} />
        <mesh geometry={nodes.sides.geometry} material={materials.fabric} position={[0.955, 0.346, 0]} />
      </group>
      <group position={[-3.97, 0.2, 0.225]} rotation={[Math.PI, 0, Math.PI]}>
        <mesh geometry={nodes.back002.geometry} material={materials.fabric} position={[0, 0.346, -0.337]} rotation={[0, 1.571, 0]} />
        <mesh geometry={nodes.Back_cousion005.geometry} material={materials.fabric} position={[-0.602, 0.566, -0.233]} rotation={[-0.244, 0, 0]} />
        <mesh geometry={nodes.Back_cousion006.geometry} material={materials.fabric} position={[0.599, 0.566, -0.233]} rotation={[-0.244, 0, 0]} />
        <mesh geometry={nodes.Back_cousion007.geometry} material={materials.fabric} position={[0, 0.566, -0.233]} rotation={[-0.244, 0, 0]} />
        <mesh geometry={nodes.bottom002.geometry} material={materials.fabric} position={[0, 0.152, 0.036]} />
        <mesh geometry={nodes.legs002.geometry} material={materials.metal} position={[0, 0.024, 0]} />
        <mesh geometry={nodes.pillow005.geometry} material={materials['pillow black']} position={[0.756, 0.539, -0.031]} rotation={[-0.334, -0.463, -0.154]} />
        <mesh geometry={nodes.pillow004.geometry} material={materials['pillow brown']} position={[0.498, 0.558, -0.03]} rotation={[-0.335, -0.338, -0.116]} />
        <mesh geometry={nodes.pillow006.geometry} material={materials['pillow black']} position={[-0.762, 0.539, -0.037]} rotation={[2.793, -0.453, -0.186]} scale={-1} />
        <mesh geometry={nodes.seat_cousion007.geometry} material={materials.fabric} position={[0.597, 0.304, 0.109]} />
        <mesh geometry={nodes.seat_cousion006.geometry} material={materials.fabric} position={[0, 0.304, 0.109]} />
        <mesh geometry={nodes.seat_cousion005.geometry} material={materials.fabric} position={[-0.599, 0.304, 0.109]} />
        <mesh geometry={nodes.sides002.geometry} material={materials.fabric} position={[0.955, 0.346, 0]} />
      </group>
      <group position={[-28.268, 0.2, -17.31]}>
        <mesh geometry={nodes.back003.geometry} material={materials.fabric} position={[0, 0.346, -0.337]} rotation={[0, 1.571, 0]} />
        <mesh geometry={nodes.Back_cousion008.geometry} material={materials.fabric} position={[-0.602, 0.566, -0.233]} rotation={[-0.244, 0, 0]} />
        <mesh geometry={nodes.Back_cousion009.geometry} material={materials.fabric} position={[0.599, 0.566, -0.233]} rotation={[-0.244, 0, 0]} />
        <mesh geometry={nodes.Back_cousion010.geometry} material={materials.fabric} position={[0, 0.566, -0.233]} rotation={[-0.244, 0, 0]} />
        <mesh geometry={nodes.bottom003.geometry} material={materials.fabric} position={[0, 0.152, 0.036]} />
        <mesh geometry={nodes.legs003.geometry} material={materials.metal} position={[0, 0.024, 0]} />
        <mesh geometry={nodes.pillow008.geometry} material={materials['pillow black']} position={[0.756, 0.539, -0.031]} rotation={[-0.334, -0.463, -0.154]} />
        <mesh geometry={nodes.pillow007.geometry} material={materials['pillow brown']} position={[0.498, 0.558, -0.03]} rotation={[-0.335, -0.338, -0.116]} />
        <mesh geometry={nodes.pillow009.geometry} material={materials['pillow black']} position={[-0.762, 0.539, -0.037]} rotation={[2.793, -0.453, -0.186]} scale={-1} />
        <mesh geometry={nodes.seat_cousion010.geometry} material={materials.fabric} position={[0.597, 0.304, 0.109]} />
        <mesh geometry={nodes.seat_cousion009.geometry} material={materials.fabric} position={[0, 0.304, 0.109]} />
        <mesh geometry={nodes.seat_cousion008.geometry} material={materials.fabric} position={[-0.599, 0.304, 0.109]} />
        <mesh geometry={nodes.sides003.geometry} material={materials.fabric} position={[0.955, 0.346, 0]} />
      </group>
      <group position={[29.864, 0.2, -15.601]} rotation={[0, -1.571, 0]}>
        <mesh geometry={nodes.back005.geometry} material={materials.fabric} position={[0, 0.346, -0.337]} rotation={[0, 1.571, 0]} />
        <mesh geometry={nodes.Back_cousion013.geometry} material={materials.fabric} position={[-0.602, 0.566, -0.233]} rotation={[-0.244, 0, 0]} />
        <mesh geometry={nodes.Back_cousion014.geometry} material={materials.fabric} position={[0.599, 0.566, -0.233]} rotation={[-0.244, 0, 0]} />
        <mesh geometry={nodes.Back_cousion015.geometry} material={materials.fabric} position={[0, 0.566, -0.233]} rotation={[-0.244, 0, 0]} />
        <mesh geometry={nodes.bottom005.geometry} material={materials.fabric} position={[0, 0.152, 0.036]} />
        <mesh geometry={nodes.legs005.geometry} material={materials.metal} position={[0, 0.024, 0]} />
        <mesh geometry={nodes.pillow012.geometry} material={materials['pillow black']} position={[0.756, 0.539, -0.031]} rotation={[-0.334, -0.463, -0.154]} />
        <mesh geometry={nodes.pillow011.geometry} material={materials['pillow brown']} position={[0.498, 0.558, -0.03]} rotation={[-0.335, -0.338, -0.116]} />
        <mesh geometry={nodes.pillow013.geometry} material={materials['pillow black']} position={[-0.762, 0.539, -0.037]} rotation={[2.793, -0.453, -0.186]} scale={-1} />
        <mesh geometry={nodes.seat_cousion015.geometry} material={materials.fabric} position={[0.597, 0.304, 0.109]} />
        <mesh geometry={nodes.seat_cousion014.geometry} material={materials.fabric} position={[0, 0.304, 0.109]} />
        <mesh geometry={nodes.seat_cousion013.geometry} material={materials.fabric} position={[-0.599, 0.304, 0.109]} />
        <mesh geometry={nodes.sides005.geometry} material={materials.fabric} position={[0.955, 0.346, 0]} />
      </group>
      <group position={[8.663, 0.2, -7.564]} rotation={[0, 1.571, 0]}>
        <mesh geometry={nodes.Back_cousion003.geometry} material={materials['fabric.001']} position={[0.302, 0.566, -0.233]} rotation={[-0.244, 0, 0]} />
        <mesh geometry={nodes.Back_cousion004.geometry} material={materials['fabric.001']} position={[-0.296, 0.566, -0.233]} rotation={[-0.244, 0, 0]} />
        <mesh geometry={nodes.back001.geometry} material={materials['fabric.001']} position={[-0.002, 0.346, -0.337]} rotation={[0, 1.571, 0]} />
        <mesh geometry={nodes.bottom001.geometry} material={materials['fabric.001']} position={[-0.001, 0.152, 0.036]} />
        <mesh geometry={nodes.legs001.geometry} material={materials['metal.001']} position={[0.656, 0.024, 0]} />
        <mesh geometry={nodes.pillow.geometry} material={materials['pillow brown.001']} position={[0.462, 0.645, -0.044]} rotation={[-0.334, -0.463, -0.154]} />
        <mesh geometry={nodes.seat_cousion003.geometry} material={materials['fabric.001']} position={[0.3, 0.304, 0.109]} />
        <mesh geometry={nodes.seat_cousion004.geometry} material={materials['fabric.001']} position={[-0.296, 0.304, 0.109]} />
        <mesh geometry={nodes.sides001.geometry} material={materials['fabric.001']} position={[0.658, 0.346, 0]} />
      </group>
      <group position={[-24.713, 0.2, -14.67]} rotation={[0, -1.571, 0]}>
        <mesh geometry={nodes.Back_cousion012.geometry} material={materials['fabric.001']} position={[0.302, 0.566, -0.233]} rotation={[-0.244, 0, 0]} />
        <mesh geometry={nodes.Back_cousion011.geometry} material={materials['fabric.001']} position={[-0.296, 0.566, -0.233]} rotation={[-0.244, 0, 0]} />
        <mesh geometry={nodes.back004.geometry} material={materials['fabric.001']} position={[-0.002, 0.346, -0.337]} rotation={[0, 1.571, 0]} />
        <mesh geometry={nodes.bottom004.geometry} material={materials['fabric.001']} position={[-0.001, 0.152, 0.036]} />
        <mesh geometry={nodes.legs004.geometry} material={materials['metal.001']} position={[0.656, 0.024, 0]} />
        <mesh geometry={nodes.pillow010.geometry} material={materials['pillow brown.001']} position={[0.462, 0.645, -0.044]} rotation={[-0.334, -0.463, -0.154]} />
        <mesh geometry={nodes.seat_cousion012.geometry} material={materials['fabric.001']} position={[0.3, 0.304, 0.109]} />
        <mesh geometry={nodes.seat_cousion011.geometry} material={materials['fabric.001']} position={[-0.296, 0.304, 0.109]} />
        <mesh geometry={nodes.sides004.geometry} material={materials['fabric.001']} position={[0.658, 0.346, 0]} />
      </group>
      <group position={[20.838, 0.2, -7.414]} rotation={[0, 1.571, 0]}>
        <mesh geometry={nodes.C_739_canapea012.geometry} material={materials['stofa canapea.cc0textires']} position={[-0.949, 0.2, 0.038]} rotation={[0, Math.PI / 2, 0]} />
        <mesh geometry={nodes.Cube.geometry} material={materials['stofa canapea.cc0textires']} position={[1.031, 0.368, -0.013]} rotation={[0, Math.PI / 2, 0]} />
        <mesh geometry={nodes.Cube001.geometry} material={materials.WOOD} position={[0.004, 0.178, -0.013]} />
        <mesh geometry={nodes.Cube004.geometry} material={materials['stofa canapea.cc0textires']} position={[0.004, 0.294, 0.043]} rotation={[0, Math.PI / 2, 0]} />
        <mesh geometry={nodes.Cube006.geometry} material={materials['stofa canapea.cc0textires']} position={[-1.027, 0.368, -0.013]} rotation={[0, Math.PI / 2, 0]} />
        <mesh geometry={nodes.perna_lowres000.geometry} material={materials['stofa canapea.002']} position={[-0.467, 0.632, -0.294]} rotation={[0, Math.PI / 2, 0]} />
        <mesh geometry={nodes.perna_lowres004.geometry} material={materials['stofa canapea.002']} position={[0.462, 0.632, -0.294]} rotation={[0, Math.PI / 2, 0]} />
        <mesh geometry={nodes.perna_mediecute_baked.geometry} material={materials['husa_perna.03']} position={[-0.578, 0.626, -0.063]} rotation={[0.45, 0, 0]} />
        <mesh geometry={nodes.perna_mediecute_baked001.geometry} material={materials['husa_perna.03']} position={[0.576, 0.591, -0.106]} rotation={[2.505, 0.972, 1.563]} />
      </group>
      <group position={[-6.432, 0.2, -8.163]} rotation={[Math.PI, 0, Math.PI]}>
        <mesh geometry={nodes.C_739_canapea012001.geometry} material={materials['stofa canapea.cc0textires']} position={[-0.949, 0.2, 0.038]} rotation={[0, Math.PI / 2, 0]} />
        <mesh geometry={nodes.Cube007.geometry} material={materials['stofa canapea.cc0textires']} position={[1.031, 0.368, -0.013]} rotation={[0, Math.PI / 2, 0]} />
        <mesh geometry={nodes.Cube005.geometry} material={materials.WOOD} position={[0.004, 0.178, -0.013]} />
        <mesh geometry={nodes.Cube002.geometry} material={materials['stofa canapea.cc0textires']} position={[-1.027, 0.368, -0.013]} rotation={[0, Math.PI / 2, 0]} />
        <mesh geometry={nodes.perna_lowres001.geometry} material={materials['stofa canapea.002']} position={[0.462, 0.632, -0.294]} rotation={[0, Math.PI / 2, 0]} />
        <mesh geometry={nodes.perna_lowres002.geometry} material={materials['stofa canapea.002']} position={[-0.467, 0.632, -0.294]} rotation={[0, Math.PI / 2, 0]} />
        <mesh geometry={nodes.perna_mediecute_baked002.geometry} material={materials['husa_perna.03']} position={[0.576, 0.591, -0.106]} rotation={[2.505, 0.972, 1.563]} />
        <mesh geometry={nodes.perna_mediecute_baked003.geometry} material={materials['husa_perna.03']} position={[-0.578, 0.626, -0.063]} rotation={[0.45, 0, 0]} />
        <mesh geometry={nodes.Cube003.geometry} material={materials['stofa canapea.cc0textires']} position={[0.004, 0.294, 0.043]} rotation={[0, Math.PI / 2, 0]} />
      </group>
      <group position={[-27.462, 0.2, 1.35]}>
        <mesh geometry={nodes.C_739_canapea012002.geometry} material={materials['stofa canapea.cc0textires']} position={[-0.949, 0.2, 0.038]} rotation={[0, Math.PI / 2, 0]} />
        <mesh geometry={nodes.Cube011.geometry} material={materials['stofa canapea.cc0textires']} position={[1.031, 0.368, -0.013]} rotation={[0, Math.PI / 2, 0]} />
        <mesh geometry={nodes.Cube010.geometry} material={materials.WOOD} position={[0.004, 0.178, -0.013]} />
        <mesh geometry={nodes.Cube008.geometry} material={materials['stofa canapea.cc0textires']} position={[-1.027, 0.368, -0.013]} rotation={[0, Math.PI / 2, 0]} />
        <mesh geometry={nodes.perna_lowres003.geometry} material={materials['stofa canapea.002']} position={[0.462, 0.632, -0.294]} rotation={[0, Math.PI / 2, 0]} />
        <mesh geometry={nodes.perna_lowres005.geometry} material={materials['stofa canapea.002']} position={[-0.467, 0.632, -0.294]} rotation={[0, Math.PI / 2, 0]} />
        <mesh geometry={nodes.perna_mediecute_baked004.geometry} material={materials['husa_perna.03']} position={[0.576, 0.591, -0.106]} rotation={[2.505, 0.972, 1.563]} />
        <mesh geometry={nodes.perna_mediecute_baked005.geometry} material={materials['husa_perna.03']} position={[-0.578, 0.626, -0.063]} rotation={[0.45, 0, 0]} />
        <mesh geometry={nodes.Cube009.geometry} material={materials['stofa canapea.cc0textires']} position={[0.004, 0.294, 0.043]} rotation={[0, Math.PI / 2, 0]} />
      </group>
      <group position={[-12.721, 0.2, -0.632]} rotation={[0, -1.571, 0]}>
        <mesh geometry={nodes.C_739_canapea012003.geometry} material={materials['stofa canapea.cc0textires']} position={[-0.949, 0.2, 0.038]} rotation={[0, Math.PI / 2, 0]} />
        <mesh geometry={nodes.Cube015.geometry} material={materials['stofa canapea.cc0textires']} position={[1.031, 0.368, -0.013]} rotation={[0, Math.PI / 2, 0]} />
        <mesh geometry={nodes.Cube014.geometry} material={materials.WOOD} position={[0.004, 0.178, -0.013]} />
        <mesh geometry={nodes.Cube012.geometry} material={materials['stofa canapea.cc0textires']} position={[-1.027, 0.368, -0.013]} rotation={[0, Math.PI / 2, 0]} />
        <mesh geometry={nodes.perna_lowres006.geometry} material={materials['stofa canapea.002']} position={[0.462, 0.632, -0.294]} rotation={[0, Math.PI / 2, 0]} />
        <mesh geometry={nodes.perna_lowres007.geometry} material={materials['stofa canapea.002']} position={[-0.467, 0.632, -0.294]} rotation={[0, Math.PI / 2, 0]} />
        <mesh geometry={nodes.perna_mediecute_baked006.geometry} material={materials['husa_perna.03']} position={[0.576, 0.591, -0.106]} rotation={[2.505, 0.972, 1.563]} />
        <mesh geometry={nodes.perna_mediecute_baked007.geometry} material={materials['husa_perna.03']} position={[-0.578, 0.626, -0.063]} rotation={[0.45, 0, 0]} />
        <mesh geometry={nodes.Cube013.geometry} material={materials['stofa canapea.cc0textires']} position={[0.004, 0.294, 0.043]} rotation={[0, Math.PI / 2, 0]} />
      </group>
      <group position={[10.272, 0.2, -7.536]} rotation={[0, 1.571, 0]}>
        <group position={[0.06, 0.495, 0.244]}>
          <mesh geometry={nodes.books_000001.geometry} material={materials['books_004.001']} />
          <mesh geometry={nodes.books_000001_1.geometry} material={materials['books_001.001']} />
          <mesh geometry={nodes.books_000001_2.geometry} material={materials['books_002.001']} />
          <mesh geometry={nodes.books_000001_3.geometry} material={materials['books_003.001']} />
          <mesh geometry={nodes.books_000001_4.geometry} material={materials['books_000.001']} />
        </group>
        <mesh geometry={nodes['table-base'].geometry} material={materials.gold} position={[0, 0.418, 0]} />
        <group position={[0, 0.022, 0]}>
          <mesh geometry={nodes.Cylinder002_1.geometry} material={materials.plastic} />
          <mesh geometry={nodes.Cylinder002_2.geometry} material={materials['Material.006']} />
        </group>
        <mesh geometry={nodes.table_wood_.geometry} material={materials.wood} position={[0, 0.463, 0]} />
        <group position={[-0.017, 0.53, -0.05]}>
          <mesh geometry={nodes.flower_vase_000001.geometry} material={materials['flower_vase_001.001']} />
          <mesh geometry={nodes.flower_vase_000001_1.geometry} material={materials['flower_vase_003.002']} />
          <mesh geometry={nodes.flower_vase_000001_2.geometry} material={materials['flower_vase_006.001']} />
          <mesh geometry={nodes.flower_vase_000001_3.geometry} material={materials['flower_vase_007.002']} />
          <mesh geometry={nodes.flower_vase_000001_4.geometry} material={materials['flower_vase_008.002']} />
          <mesh geometry={nodes.flower_vase_000001_5.geometry} material={materials['flower_vase_009.002']} />
        </group>
      </group>
      <group position={[-4.001, 0.2, -0.93]} rotation={[Math.PI, 0, Math.PI]} scale={0.5}>
        <mesh geometry={nodes.Circle.geometry} material={materials.Wood} rotation={[Math.PI / 4, 0, 0]} />
        <mesh geometry={nodes.Circle001.geometry} material={materials.Wood} rotation={[-Math.PI / 4, 0, -Math.PI]} />
        <mesh geometry={nodes.Circle002.geometry} material={materials.Glass} position={[0, 0.731, 0]} />
        <mesh geometry={nodes.Circle003.geometry} material={materials.Silicone} position={[0.1, 0.721, -0.346]} />
        <mesh geometry={nodes.Circle004.geometry} material={materials.Silicone} position={[-0.5, 0.721, -0.346]} />
        <mesh geometry={nodes.Circle005.geometry} material={materials.Silicone} position={[0.5, 0.721, 0.347]} />
        <mesh geometry={nodes.Circle006.geometry} material={materials.Silicone} position={[-0.1, 0.721, 0.347]} />
      </group>
      <group position={[22.296, 0.2, -7.414]} rotation={[0, Math.PI / 2, 0]} scale={0.5}>
        <mesh geometry={nodes.Circle013.geometry} material={materials.Wood} rotation={[Math.PI / 4, 0, 0]} />
        <mesh geometry={nodes.Circle012.geometry} material={materials.Wood} rotation={[-Math.PI / 4, 0, -Math.PI]} />
        <mesh geometry={nodes.Circle011.geometry} material={materials.Glass} position={[0, 0.731, 0]} />
        <mesh geometry={nodes.Circle007.geometry} material={materials.Silicone} position={[-0.1, 0.721, 0.347]} />
        <mesh geometry={nodes.Circle008.geometry} material={materials.Silicone} position={[0.5, 0.721, 0.347]} />
        <mesh geometry={nodes.Circle009.geometry} material={materials.Silicone} position={[-0.5, 0.721, -0.346]} />
        <mesh geometry={nodes.Circle010.geometry} material={materials.Silicone} position={[0.1, 0.721, -0.346]} />
      </group>
      <group position={[27.75, 0.2, -15.599]} rotation={[0, -1.571, 0]}>
        <mesh geometry={nodes.Bottom.geometry} material={materials['Steel brushed scratched_SMR.004']} position={[0, 0.032, 0]} scale={[0.494, 0.148, 0.494]} />
        <mesh geometry={nodes.Cylinder001.geometry} material={materials['Material.001']} position={[0, -0.003, 0]} rotation={[0, 1.113, 0]} scale={[0.009, 0.003, 0.009]} />
        <mesh geometry={nodes.Cylinder002.geometry} material={materials['Material.001']} position={[0, -0.003, 0]} rotation={[0, 0.917, 0]} scale={[0.009, 0.003, 0.009]} />
        <mesh geometry={nodes.Cylinder003.geometry} material={materials['Material.001']} position={[0, -0.003, 0]} rotation={[0, 0.72, 0]} scale={[0.009, 0.003, 0.009]} />
        <mesh geometry={nodes.Cylinder004.geometry} material={materials['Material.001']} position={[0, -0.003, 0]} rotation={[0, 0.524, 0]} scale={[0.009, 0.003, 0.009]} />
        <mesh geometry={nodes.Cylinder005.geometry} material={materials['Material.001']} position={[0, -0.003, 0]} rotation={[0, 0.328, 0]} scale={[0.009, 0.003, 0.009]} />
        <mesh geometry={nodes.Cylinder006.geometry} material={materials['Material.001']} position={[0, -0.003, 0]} rotation={[0, 0.131, 0]} scale={[0.009, 0.003, 0.009]} />
        <mesh geometry={nodes.Cylinder007.geometry} material={materials['Material.001']} position={[0, -0.003, 0]} rotation={[0, -0.065, 0]} scale={[0.009, 0.003, 0.009]} />
        <mesh geometry={nodes.Cylinder008.geometry} material={materials['Material.001']} position={[0, -0.003, 0]} rotation={[0, -0.262, 0]} scale={[0.009, 0.003, 0.009]} />
        <mesh geometry={nodes.Cylinder009.geometry} material={materials['Material.001']} position={[0, -0.003, 0]} rotation={[0, -0.458, 0]} scale={[0.009, 0.003, 0.009]} />
        <mesh geometry={nodes.Cylinder010.geometry} material={materials['Material.001']} position={[0, -0.003, 0]} rotation={[0, -0.654, 0]} scale={[0.009, 0.003, 0.009]} />
        <mesh geometry={nodes.Cylinder011.geometry} material={materials['Material.001']} position={[0, -0.003, 0]} rotation={[0, -0.851, 0]} scale={[0.009, 0.003, 0.009]} />
        <mesh geometry={nodes.Cylinder012.geometry} material={materials['Material.001']} position={[0, -0.003, 0]} rotation={[0, -1.047, 0]} scale={[0.009, 0.003, 0.009]} />
        <mesh geometry={nodes.Cylinder013.geometry} material={materials['Material.001']} position={[0, -0.003, 0]} rotation={[0, -1.243, 0]} scale={[0.009, 0.003, 0.009]} />
        <mesh geometry={nodes.Cylinder014.geometry} material={materials['Material.001']} position={[0, -0.003, 0]} rotation={[0, -1.44, 0]} scale={[0.009, 0.003, 0.009]} />
        <mesh geometry={nodes.Cylinder015.geometry} material={materials['Material.001']} position={[0, -0.003, 0]} rotation={[Math.PI, -1.506, Math.PI]} scale={[0.009, 0.003, 0.009]} />
        <mesh geometry={nodes.Cylinder016.geometry} material={materials['Material.001']} position={[0, -0.003, 0]} rotation={[Math.PI, -0.917, Math.PI]} scale={[0.009, 0.003, 0.009]} />
        <mesh geometry={nodes.Cylinder017.geometry} material={materials['Material.001']} position={[0, -0.003, 0]} rotation={[Math.PI, -0.524, Math.PI]} scale={[0.009, 0.003, 0.009]} />
        <mesh geometry={nodes.Cylinder018.geometry} material={materials['Material.001']} position={[0, -0.003, 0]} rotation={[Math.PI, -0.131, Math.PI]} scale={[0.009, 0.003, 0.009]} />
        <mesh geometry={nodes.Cylinder019.geometry} material={materials['Material.001']} position={[0, -0.003, 0]} rotation={[0, 1.309, 0]} scale={[0.009, 0.003, 0.009]} />
        <mesh geometry={nodes.Cylinder020.geometry} material={materials['Material.001']} position={[0, -0.003, 0]} rotation={[-Math.PI, 0.065, -Math.PI]} scale={[0.009, 0.003, 0.009]} />
        <mesh geometry={nodes.Cylinder021.geometry} material={materials['Material.001']} position={[0, -0.003, 0]} rotation={[-Math.PI, 0.262, -Math.PI]} scale={[0.009, 0.003, 0.009]} />
        <mesh geometry={nodes.Cylinder022.geometry} material={materials['Material.001']} position={[0, -0.003, 0]} rotation={[-Math.PI, 0.458, -Math.PI]} scale={[0.009, 0.003, 0.009]} />
        <mesh geometry={nodes.Cylinder023.geometry} material={materials['Material.001']} position={[0, -0.003, 0]} rotation={[-Math.PI, 0.654, -Math.PI]} scale={[0.009, 0.003, 0.009]} />
        <mesh geometry={nodes.Cylinder024.geometry} material={materials['Material.001']} position={[0, -0.003, 0]} rotation={[Math.PI, -1.309, Math.PI]} scale={[0.009, 0.003, 0.009]} />
        <mesh geometry={nodes.Cylinder025.geometry} material={materials['Material.001']} position={[0, -0.003, 0]} rotation={[Math.PI, -1.113, Math.PI]} scale={[0.009, 0.003, 0.009]} />
        <mesh geometry={nodes.Cylinder026.geometry} material={materials['Material.001']} position={[0, -0.003, 0]} rotation={[Math.PI, -0.72, Math.PI]} scale={[0.009, 0.003, 0.009]} />
        <mesh geometry={nodes.Cylinder027.geometry} material={materials['Material.001']} position={[0, -0.003, 0]} rotation={[Math.PI, -0.328, Math.PI]} scale={[0.009, 0.003, 0.009]} />
        <mesh geometry={nodes.Cylinder028.geometry} material={materials['Material.001']} position={[0, -0.003, 0]} rotation={[-Math.PI, 0.851, -Math.PI]} scale={[0.009, 0.003, 0.009]} />
        <mesh geometry={nodes.Cylinder029.geometry} material={materials['Material.001']} position={[0, -0.003, 0]} rotation={[-Math.PI, 1.047, -Math.PI]} scale={[0.009, 0.003, 0.009]} />
        <mesh geometry={nodes.Cylinder030.geometry} material={materials['Material.001']} position={[0, -0.003, 0]} rotation={[-Math.PI, 1.243, -Math.PI]} scale={[0.009, 0.003, 0.009]} />
        <mesh geometry={nodes.Cylinder031.geometry} material={materials['Material.001']} position={[0, -0.003, 0]} rotation={[-Math.PI, 1.44, -Math.PI]} scale={[0.009, 0.003, 0.009]} />
        <mesh geometry={nodes.Cylinder032.geometry} material={materials['Material.001']} position={[0, -0.003, 0]} rotation={[0, 1.506, 0]} scale={[0.009, 0.003, 0.009]} />
        <mesh geometry={nodes.Foot.geometry} material={materials['Steel brushed scratched_SMR.004']} position={[0, 0.24, 0]} scale={[0.098, 0.117, 0.098]} />
        <mesh geometry={nodes.Top.geometry} material={materials['Material_SMR.004']} position={[0, 0.058, 0]} rotation={[0, -1.062, 0]} />
        <mesh geometry={nodes.Top_rest.geometry} material={materials['Steel brushed scratched_SMR.004']} position={[0, 0.426, 0]} scale={0.587} />
      </group>
      <group position={[3.217, 0.2, -17.331]}>
        <mesh geometry={nodes.Cube022_1.geometry} material={materials['Black Metal']} />
        <mesh geometry={nodes.Cube022_2.geometry} material={materials['rubber feet']} />
        <mesh geometry={nodes.Cube021_1.geometry} material={materials['top wood']} />
        <mesh geometry={nodes.Cube021_2.geometry} material={materials['bottom wood']} />
      </group>
      <group position={[18.664, 0.2, -17.379]}>
        <mesh geometry={nodes.Cube022_3.geometry} material={materials['Black Metal']} />
        <mesh geometry={nodes.Cube022_4.geometry} material={materials['rubber feet']} />
        <mesh geometry={nodes.Cube021_3.geometry} material={materials['top wood']} />
        <mesh geometry={nodes.Cube021_4.geometry} material={materials['bottom wood']} />
      </group>
      <group position={[-1.373, 0.2, -12.651]} rotation={[0, 1.571, 0]}>
        <mesh geometry={nodes.Cube016.geometry} material={materials['Material.003']} />
        <mesh geometry={nodes.Cube017.geometry} material={materials['Material.003']} />
        <mesh geometry={nodes.Cube018.geometry} material={materials['Material.005']} />
        <mesh geometry={nodes.Cylinder.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.Ladder.geometry} material={materials['Material.004']} />
      </group>
      <group position={[-2.568, 0.2, -13.993]} rotation={[0, -1.571, 0]}>
        <mesh geometry={nodes.Cube019.geometry} material={materials['Material.003']} />
        <mesh geometry={nodes.Cube020.geometry} material={materials['Material.003']} />
        <mesh geometry={nodes.Cube021.geometry} material={materials['Material.005']} />
        <mesh geometry={nodes.Cylinder033.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.Ladder001.geometry} material={materials['Material.004']} />
      </group>
      <group position={[-19.004, 0.2, -17.23]}>
        <mesh geometry={nodes.Cube022.geometry} material={materials['Material.003']} />
        <mesh geometry={nodes.Cube023.geometry} material={materials['Material.003']} />
        <mesh geometry={nodes.Cube024.geometry} material={materials['Material.005']} />
        <mesh geometry={nodes.Cylinder034.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.Ladder002.geometry} material={materials['Material.004']} />
      </group>
      <group position={[17.335, 0.2, 1.314]}>
        <mesh geometry={nodes.Cube028.geometry} material={materials['Material.003']} />
        <mesh geometry={nodes.Cube029.geometry} material={materials['Material.003']} />
        <mesh geometry={nodes.Cube030.geometry} material={materials['Material.005']} />
        <mesh geometry={nodes.Cylinder037.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.Ladder003.geometry} material={materials['Material.004']} />
      </group>
      <group position={[-24.78, 0.2, -3.492]} rotation={[0, -1.571, 0]}>
        <mesh geometry={nodes.Cube031.geometry} material={materials['Material.003']} />
        <mesh geometry={nodes.Cube032.geometry} material={materials['Material.003']} />
        <mesh geometry={nodes.Cube033.geometry} material={materials['Material.005']} />
        <mesh geometry={nodes.Cylinder038.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.Ladder004.geometry} material={materials['Material.004']} />
      </group>
      <group position={[-12.74, 0.2, -5.302]} scale={0.43}>
        <mesh geometry={nodes.Cube025.geometry} material={materials['Bookshelf_metal ']} position={[0.387, 3.747, 0.013]} scale={2.325} />
        <mesh geometry={nodes.Cube026.geometry} material={materials['Bookshelf_metal ']} position={[0.387, 3.747, 0.013]} scale={2.325} />
        <mesh geometry={nodes.Cube027.geometry} material={materials.Bookshelf_Wood} scale={2.325} />
        <mesh geometry={nodes.Cylinder035.geometry} material={materials.Bookshelf_aluminum} position={[-0.443, 1.421, 0.011]} rotation={[0, 0, Math.PI]} scale={2.325} />
        <mesh geometry={nodes.Cylinder036.geometry} material={nodes.Cylinder036.material} position={[-0.443, 1.426, 0.011]} scale={[1.567, 0.01, 1.567]} />
      </group>
      <mesh geometry={nodes.Floor_1.geometry} material={materials['Wall Paint (White Wall Paint)']} position={[0, 0, -0.193]} scale={[0.99, 1.11, 1]} />
      <mesh geometry={nodes.Floor_2.geometry} material={materials._White} position={[-0.518, 5.18, -6.359]} scale={[0.625, 1.808, 0.478]} />
      <mesh geometry={nodes.Floor_3.geometry} material={materials.Mirror} position={[-0.691, 9.432, -6.19]} scale={[0.625, 3.535, 0.479]} />
      <group position={[2.927, 0.2, 6.141]} rotation={[Math.PI, 0, Math.PI]}>
        <mesh geometry={nodes.pot.geometry} material={materials.pot} />
        <mesh geometry={nodes.pot_1.geometry} material={materials.GROUND} />
        <mesh geometry={nodes.plant.geometry} material={materials['leaf.001']} position={[-0.167, 2.19, 0.052]} />
        <mesh geometry={nodes.plant001.geometry} material={materials['leaf.001']} position={[-0.449, 2.364, 0.039]} />
        <mesh geometry={nodes.plant002.geometry} material={materials['leaf.001']} position={[-0.191, 2.048, -0.136]} />
        <mesh geometry={nodes.plant003.geometry} material={materials['leaf.001']} position={[0.526, 1.805, -0.117]} />
        <mesh geometry={nodes.plant004.geometry} material={materials['leaf.001']} position={[-0.139, 1.927, -0.656]} />
        <mesh geometry={nodes.plant005.geometry} material={materials['trunk.001']} position={[0.022, 1.297, 0.01]} />
        <mesh geometry={nodes.plant006.geometry} material={materials['trunk.001']} position={[0.022, 1.297, 0.01]} />
        <mesh geometry={nodes.plant007.geometry} material={materials['leaf.001']} position={[-0.367, 0.813, -0.225]} />
        <mesh geometry={nodes.plant008.geometry} material={materials['leaf.001']} position={[0.173, 1.656, 0.34]} />
        <mesh geometry={nodes.plant009.geometry} material={materials['leaf.001']} position={[0.336, 0.782, -0.304]} />
        <mesh geometry={nodes.plant010.geometry} material={materials['leaf.001']} position={[0.586, 1.124, -0.035]} />
        <mesh geometry={nodes.plant011.geometry} material={materials['leaf.001']} position={[-0.091, 1.046, -0.016]} />
        <mesh geometry={nodes.plant012.geometry} material={materials['leaf.001']} position={[-0.326, 1.425, 0.168]} />
        <mesh geometry={nodes.plant013.geometry} material={materials['leaf.001']} position={[0.418, 1.031, 0.257]} />
        <mesh geometry={nodes.plant014.geometry} material={materials['leaf.001']} position={[0.119, 1.912, -0.227]} />
        <mesh geometry={nodes.plant015.geometry} material={materials['leaf.001']} position={[-0.461, 1.752, 0.239]} />
        <mesh geometry={nodes.plant016.geometry} material={materials['leaf.001']} position={[-0.279, 1.77, -0.014]} />
        <mesh geometry={nodes.plant017.geometry} material={materials['leaf.001']} position={[-0.008, 1.262, 0.135]} />
        <mesh geometry={nodes.plant024.geometry} material={materials['leaf.001']} position={[0.113, 1.621, -0.015]} />
        <mesh geometry={nodes.plant026.geometry} material={materials['leaf.001']} position={[0.05, 2.181, -0.064]} />
        <mesh geometry={nodes.plant028.geometry} material={materials['leaf.001']} position={[0.314, 2.241, -0.227]} />
        <mesh geometry={nodes.plant029.geometry} material={materials['leaf.001']} position={[-0.151, 0.969, -0.171]} />
        <mesh geometry={nodes.plant030.geometry} material={materials['leaf.001']} position={[0.182, 1.665, -0.084]} />
        <mesh geometry={nodes.plant031.geometry} material={materials['leaf.001']} position={[0.331, 1.305, -0.436]} />
        <mesh geometry={nodes.plant032.geometry} material={materials['leaf.001']} position={[0.321, 1.729, -0.531]} />
        <mesh geometry={nodes.plant033.geometry} material={materials['leaf.001']} position={[0.243, 1.935, 0.132]} />
        <mesh geometry={nodes.plant034.geometry} material={materials['leaf.001']} position={[-0.347, 1.173, 0.006]} />
        <mesh geometry={nodes.plant035.geometry} material={materials['leaf.001']} position={[0.005, 1.137, 0.454]} />
        <mesh geometry={nodes.plant036.geometry} material={materials['leaf.001']} position={[0.149, 1.092, -0.203]} />
        <mesh geometry={nodes.plant037.geometry} material={materials['leaf.001']} position={[0.124, 1.193, -0.207]} />
        <mesh geometry={nodes.plant038.geometry} material={materials['leaf.001']} position={[-0.33, 1.624, 0.658]} />
        <mesh geometry={nodes.plant039.geometry} material={materials['leaf.001']} position={[-0.251, 1.591, -0.222]} />
        <mesh geometry={nodes.plant040.geometry} material={materials['leaf.001']} position={[-0.476, 1.517, -0.354]} />
        <mesh geometry={nodes.plant041.geometry} material={materials['leaf.001']} position={[-0.093, 1.451, 0.361]} />
        <mesh geometry={nodes.plant042.geometry} material={materials['leaf.001']} position={[0.036, 1.734, -0.017]} />
        <mesh geometry={nodes.plant043.geometry} material={materials['leaf.001']} position={[-0.128, 2.081, 0.248]} />
        <mesh geometry={nodes.plant044.geometry} material={materials['leaf.001']} position={[0.251, 1.182, 0.182]} />
        <mesh geometry={nodes.plant045.geometry} material={materials['leaf.001']} position={[0.196, 0.867, -0.134]} />
        <mesh geometry={nodes.plant046.geometry} material={materials['leaf.001']} position={[0.267, 1.332, 0.314]} />
        <mesh geometry={nodes.plant047.geometry} material={materials['leaf.001']} position={[0.302, 1.035, -0.048]} />
        <mesh geometry={nodes.plant048.geometry} material={materials['leaf.001']} position={[-0.076, 1.407, 0.178]} />
        <mesh geometry={nodes.plant049.geometry} material={materials['leaf.001']} position={[0.637, 1.467, -0.078]} />
        <mesh geometry={nodes.plant050.geometry} material={materials['leaf.001']} position={[-0.059, 1.539, -0.357]} />
        <mesh geometry={nodes.plant051.geometry} material={materials['trunk.001']} position={[0.022, 1.297, 0.01]} />
        <mesh geometry={nodes.plant052.geometry} material={materials['leaf.001']} position={[0.052, 1.043, -0.56]} />
        <mesh geometry={nodes.plant053.geometry} material={materials['leaf.001']} position={[-0.064, 1.752, -0.338]} />
        <mesh geometry={nodes.plant054.geometry} material={materials['leaf.001']} position={[0.329, 1.372, 0.048]} />
        <mesh geometry={nodes.plant055.geometry} material={materials['leaf.001']} position={[-0.064, 1.469, -0.625]} />
        <mesh geometry={nodes.plant056.geometry} material={materials['leaf.001']} position={[0.041, 1.072, 0.161]} />
        <mesh geometry={nodes.plant057.geometry} material={materials['leaf.001']} position={[-0.104, 2.178, 0.239]} />
        <mesh geometry={nodes.plant058.geometry} material={materials['leaf.001']} position={[-0.121, 2.39, 0.465]} />
        <mesh geometry={nodes.plant059.geometry} material={materials['leaf.001']} position={[0.023, 2.208, 0.016]} />
        <mesh geometry={nodes.plant060.geometry} material={materials['leaf.001']} position={[0.253, 2.489, 0.03]} />
        <mesh geometry={nodes.plant061.geometry} material={materials['trunk.001']} position={[0.022, 1.297, 0.01]} />
        <mesh geometry={nodes.plant062.geometry} material={materials['leaf.001']} position={[-0.266, 2.041, -0.412]} />
        <mesh geometry={nodes.plant063.geometry} material={materials['leaf.001']} position={[-0.082, 1.985, 0.441]} />
      </group>
      <group position={[-2.65, 0.2, 6.159]} rotation={[Math.PI, 0, Math.PI]}>
        <mesh geometry={nodes.pot.geometry} material={materials.pot} />
        <mesh geometry={nodes.pot_1.geometry} material={materials.GROUND} />
        <mesh geometry={nodes.plant111.geometry} material={materials['leaf.001']} position={[-0.167, 2.19, 0.052]} />
        <mesh geometry={nodes.plant110.geometry} material={materials['leaf.001']} position={[-0.449, 2.364, 0.039]} />
        <mesh geometry={nodes.plant109.geometry} material={materials['leaf.001']} position={[-0.191, 2.048, -0.136]} />
        <mesh geometry={nodes.plant108.geometry} material={materials['leaf.001']} position={[0.526, 1.805, -0.117]} />
        <mesh geometry={nodes.plant107.geometry} material={materials['leaf.001']} position={[-0.139, 1.927, -0.656]} />
        <mesh geometry={nodes.plant106.geometry} material={materials['trunk.001']} position={[0.022, 1.297, 0.01]} />
        <mesh geometry={nodes.plant105.geometry} material={materials['trunk.001']} position={[0.022, 1.297, 0.01]} />
        <mesh geometry={nodes.plant104.geometry} material={materials['leaf.001']} position={[-0.367, 0.813, -0.225]} />
        <mesh geometry={nodes.plant103.geometry} material={materials['leaf.001']} position={[0.173, 1.656, 0.34]} />
        <mesh geometry={nodes.plant102.geometry} material={materials['leaf.001']} position={[0.336, 0.782, -0.304]} />
        <mesh geometry={nodes.plant101.geometry} material={materials['leaf.001']} position={[0.586, 1.124, -0.035]} />
        <mesh geometry={nodes.plant100.geometry} material={materials['leaf.001']} position={[-0.091, 1.046, -0.016]} />
        <mesh geometry={nodes.plant099.geometry} material={materials['leaf.001']} position={[-0.326, 1.425, 0.168]} />
        <mesh geometry={nodes.plant098.geometry} material={materials['leaf.001']} position={[0.418, 1.031, 0.257]} />
        <mesh geometry={nodes.plant097.geometry} material={materials['leaf.001']} position={[0.119, 1.912, -0.227]} />
        <mesh geometry={nodes.plant096.geometry} material={materials['leaf.001']} position={[-0.461, 1.752, 0.239]} />
        <mesh geometry={nodes.plant095.geometry} material={materials['leaf.001']} position={[-0.279, 1.77, -0.014]} />
        <mesh geometry={nodes.plant094.geometry} material={materials['leaf.001']} position={[-0.008, 1.262, 0.135]} />
        <mesh geometry={nodes.plant093.geometry} material={materials['leaf.001']} position={[0.113, 1.621, -0.015]} />
        <mesh geometry={nodes.plant092.geometry} material={materials['leaf.001']} position={[0.05, 2.181, -0.064]} />
        <mesh geometry={nodes.plant091.geometry} material={materials['leaf.001']} position={[0.314, 2.241, -0.227]} />
        <mesh geometry={nodes.plant090.geometry} material={materials['leaf.001']} position={[-0.151, 0.969, -0.171]} />
        <mesh geometry={nodes.plant089.geometry} material={materials['leaf.001']} position={[0.182, 1.665, -0.084]} />
        <mesh geometry={nodes.plant088.geometry} material={materials['leaf.001']} position={[0.331, 1.305, -0.436]} />
        <mesh geometry={nodes.plant087.geometry} material={materials['leaf.001']} position={[0.321, 1.729, -0.531]} />
        <mesh geometry={nodes.plant086.geometry} material={materials['leaf.001']} position={[0.243, 1.935, 0.132]} />
        <mesh geometry={nodes.plant085.geometry} material={materials['leaf.001']} position={[-0.347, 1.173, 0.006]} />
        <mesh geometry={nodes.plant084.geometry} material={materials['leaf.001']} position={[0.005, 1.137, 0.454]} />
        <mesh geometry={nodes.plant083.geometry} material={materials['leaf.001']} position={[0.149, 1.092, -0.203]} />
        <mesh geometry={nodes.plant082.geometry} material={materials['leaf.001']} position={[0.124, 1.193, -0.207]} />
        <mesh geometry={nodes.plant081.geometry} material={materials['leaf.001']} position={[-0.33, 1.624, 0.658]} />
        <mesh geometry={nodes.plant080.geometry} material={materials['leaf.001']} position={[-0.251, 1.591, -0.222]} />
        <mesh geometry={nodes.plant079.geometry} material={materials['leaf.001']} position={[-0.476, 1.517, -0.354]} />
        <mesh geometry={nodes.plant078.geometry} material={materials['leaf.001']} position={[-0.093, 1.451, 0.361]} />
        <mesh geometry={nodes.plant077.geometry} material={materials['leaf.001']} position={[0.036, 1.734, -0.017]} />
        <mesh geometry={nodes.plant076.geometry} material={materials['leaf.001']} position={[-0.128, 2.081, 0.248]} />
        <mesh geometry={nodes.plant075.geometry} material={materials['leaf.001']} position={[0.251, 1.182, 0.182]} />
        <mesh geometry={nodes.plant074.geometry} material={materials['leaf.001']} position={[0.196, 0.867, -0.134]} />
        <mesh geometry={nodes.plant073.geometry} material={materials['leaf.001']} position={[0.267, 1.332, 0.314]} />
        <mesh geometry={nodes.plant072.geometry} material={materials['leaf.001']} position={[0.302, 1.035, -0.048]} />
        <mesh geometry={nodes.plant071.geometry} material={materials['leaf.001']} position={[-0.076, 1.407, 0.178]} />
        <mesh geometry={nodes.plant070.geometry} material={materials['leaf.001']} position={[0.637, 1.467, -0.078]} />
        <mesh geometry={nodes.plant069.geometry} material={materials['leaf.001']} position={[-0.059, 1.539, -0.357]} />
        <mesh geometry={nodes.plant068.geometry} material={materials['trunk.001']} position={[0.022, 1.297, 0.01]} />
        <mesh geometry={nodes.plant067.geometry} material={materials['leaf.001']} position={[0.052, 1.043, -0.56]} />
        <mesh geometry={nodes.plant066.geometry} material={materials['leaf.001']} position={[-0.064, 1.752, -0.338]} />
        <mesh geometry={nodes.plant065.geometry} material={materials['leaf.001']} position={[0.329, 1.372, 0.048]} />
        <mesh geometry={nodes.plant064.geometry} material={materials['leaf.001']} position={[-0.064, 1.469, -0.625]} />
        <mesh geometry={nodes.plant027.geometry} material={materials['leaf.001']} position={[0.041, 1.072, 0.161]} />
        <mesh geometry={nodes.plant025.geometry} material={materials['leaf.001']} position={[-0.104, 2.178, 0.239]} />
        <mesh geometry={nodes.plant023.geometry} material={materials['leaf.001']} position={[-0.121, 2.39, 0.465]} />
        <mesh geometry={nodes.plant022.geometry} material={materials['leaf.001']} position={[0.023, 2.208, 0.016]} />
        <mesh geometry={nodes.plant021.geometry} material={materials['leaf.001']} position={[0.253, 2.489, 0.03]} />
        <mesh geometry={nodes.plant020.geometry} material={materials['trunk.001']} position={[0.022, 1.297, 0.01]} />
        <mesh geometry={nodes.plant019.geometry} material={materials['leaf.001']} position={[-0.266, 2.041, -0.412]} />
        <mesh geometry={nodes.plant018.geometry} material={materials['leaf.001']} position={[-0.082, 1.985, 0.441]} />
      </group>
      <group position={[15.315, 0.2, -16.904]} rotation={[0, -1.571, 0]}>
        <mesh geometry={nodes.pot.geometry} material={materials.pot} />
        <mesh geometry={nodes.pot_1.geometry} material={materials.GROUND} />
        <mesh geometry={nodes.plant167.geometry} material={materials['leaf.001']} position={[-0.167, 2.19, 0.052]} />
        <mesh geometry={nodes.plant166.geometry} material={materials['leaf.001']} position={[-0.449, 2.364, 0.039]} />
        <mesh geometry={nodes.plant165.geometry} material={materials['leaf.001']} position={[-0.191, 2.048, -0.136]} />
        <mesh geometry={nodes.plant164.geometry} material={materials['leaf.001']} position={[0.526, 1.805, -0.117]} />
        <mesh geometry={nodes.plant163.geometry} material={materials['leaf.001']} position={[-0.139, 1.927, -0.656]} />
        <mesh geometry={nodes.plant162.geometry} material={materials['trunk.001']} position={[0.022, 1.297, 0.01]} />
        <mesh geometry={nodes.plant161.geometry} material={materials['trunk.001']} position={[0.022, 1.297, 0.01]} />
        <mesh geometry={nodes.plant160.geometry} material={materials['leaf.001']} position={[-0.367, 0.813, -0.225]} />
        <mesh geometry={nodes.plant159.geometry} material={materials['leaf.001']} position={[0.173, 1.656, 0.34]} />
        <mesh geometry={nodes.plant158.geometry} material={materials['leaf.001']} position={[0.336, 0.782, -0.304]} />
        <mesh geometry={nodes.plant157.geometry} material={materials['leaf.001']} position={[0.586, 1.124, -0.035]} />
        <mesh geometry={nodes.plant156.geometry} material={materials['leaf.001']} position={[-0.091, 1.046, -0.016]} />
        <mesh geometry={nodes.plant155.geometry} material={materials['leaf.001']} position={[-0.326, 1.425, 0.168]} />
        <mesh geometry={nodes.plant154.geometry} material={materials['leaf.001']} position={[0.418, 1.031, 0.257]} />
        <mesh geometry={nodes.plant153.geometry} material={materials['leaf.001']} position={[0.119, 1.912, -0.227]} />
        <mesh geometry={nodes.plant152.geometry} material={materials['leaf.001']} position={[-0.461, 1.752, 0.239]} />
        <mesh geometry={nodes.plant151.geometry} material={materials['leaf.001']} position={[-0.279, 1.77, -0.014]} />
        <mesh geometry={nodes.plant150.geometry} material={materials['leaf.001']} position={[-0.008, 1.262, 0.135]} />
        <mesh geometry={nodes.plant149.geometry} material={materials['leaf.001']} position={[0.113, 1.621, -0.015]} />
        <mesh geometry={nodes.plant148.geometry} material={materials['leaf.001']} position={[0.05, 2.181, -0.064]} />
        <mesh geometry={nodes.plant147.geometry} material={materials['leaf.001']} position={[0.314, 2.241, -0.227]} />
        <mesh geometry={nodes.plant146.geometry} material={materials['leaf.001']} position={[-0.151, 0.969, -0.171]} />
        <mesh geometry={nodes.plant145.geometry} material={materials['leaf.001']} position={[0.182, 1.665, -0.084]} />
        <mesh geometry={nodes.plant144.geometry} material={materials['leaf.001']} position={[0.331, 1.305, -0.436]} />
        <mesh geometry={nodes.plant143.geometry} material={materials['leaf.001']} position={[0.321, 1.729, -0.531]} />
        <mesh geometry={nodes.plant142.geometry} material={materials['leaf.001']} position={[0.243, 1.935, 0.132]} />
        <mesh geometry={nodes.plant141.geometry} material={materials['leaf.001']} position={[-0.347, 1.173, 0.006]} />
        <mesh geometry={nodes.plant140.geometry} material={materials['leaf.001']} position={[0.005, 1.137, 0.454]} />
        <mesh geometry={nodes.plant139.geometry} material={materials['leaf.001']} position={[0.149, 1.092, -0.203]} />
        <mesh geometry={nodes.plant138.geometry} material={materials['leaf.001']} position={[0.124, 1.193, -0.207]} />
        <mesh geometry={nodes.plant137.geometry} material={materials['leaf.001']} position={[-0.33, 1.624, 0.658]} />
        <mesh geometry={nodes.plant136.geometry} material={materials['leaf.001']} position={[-0.251, 1.591, -0.222]} />
        <mesh geometry={nodes.plant135.geometry} material={materials['leaf.001']} position={[-0.476, 1.517, -0.354]} />
        <mesh geometry={nodes.plant134.geometry} material={materials['leaf.001']} position={[-0.093, 1.451, 0.361]} />
        <mesh geometry={nodes.plant133.geometry} material={materials['leaf.001']} position={[0.036, 1.734, -0.017]} />
        <mesh geometry={nodes.plant132.geometry} material={materials['leaf.001']} position={[-0.128, 2.081, 0.248]} />
        <mesh geometry={nodes.plant131.geometry} material={materials['leaf.001']} position={[0.251, 1.182, 0.182]} />
        <mesh geometry={nodes.plant130.geometry} material={materials['leaf.001']} position={[0.196, 0.867, -0.134]} />
        <mesh geometry={nodes.plant129.geometry} material={materials['leaf.001']} position={[0.267, 1.332, 0.314]} />
        <mesh geometry={nodes.plant128.geometry} material={materials['leaf.001']} position={[0.302, 1.035, -0.048]} />
        <mesh geometry={nodes.plant127.geometry} material={materials['leaf.001']} position={[-0.076, 1.407, 0.178]} />
        <mesh geometry={nodes.plant126.geometry} material={materials['leaf.001']} position={[0.637, 1.467, -0.078]} />
        <mesh geometry={nodes.plant125.geometry} material={materials['leaf.001']} position={[-0.059, 1.539, -0.357]} />
        <mesh geometry={nodes.plant124.geometry} material={materials['trunk.001']} position={[0.022, 1.297, 0.01]} />
        <mesh geometry={nodes.plant123.geometry} material={materials['leaf.001']} position={[0.052, 1.043, -0.56]} />
        <mesh geometry={nodes.plant122.geometry} material={materials['leaf.001']} position={[-0.064, 1.752, -0.338]} />
        <mesh geometry={nodes.plant121.geometry} material={materials['leaf.001']} position={[0.329, 1.372, 0.048]} />
        <mesh geometry={nodes.plant120.geometry} material={materials['leaf.001']} position={[-0.064, 1.469, -0.625]} />
        <mesh geometry={nodes.plant119.geometry} material={materials['leaf.001']} position={[0.041, 1.072, 0.161]} />
        <mesh geometry={nodes.plant118.geometry} material={materials['leaf.001']} position={[-0.104, 2.178, 0.239]} />
        <mesh geometry={nodes.plant117.geometry} material={materials['leaf.001']} position={[-0.121, 2.39, 0.465]} />
        <mesh geometry={nodes.plant116.geometry} material={materials['leaf.001']} position={[0.023, 2.208, 0.016]} />
        <mesh geometry={nodes.plant115.geometry} material={materials['leaf.001']} position={[0.253, 2.489, 0.03]} />
        <mesh geometry={nodes.plant114.geometry} material={materials['trunk.001']} position={[0.022, 1.297, 0.01]} />
        <mesh geometry={nodes.plant113.geometry} material={materials['leaf.001']} position={[-0.266, 2.041, -0.412]} />
        <mesh geometry={nodes.plant112.geometry} material={materials['leaf.001']} position={[-0.082, 1.985, 0.441]} />
      </group>
      <mesh geometry={nodes.Metal_Bookshelf.geometry} material={materials['Liquid Metal Material']} position={[17.661, 0.2, -3.066]}>
        <mesh geometry={nodes.Metal_bookshelf_Windows.geometry} material={materials['Windows Material']} position={[0, 0.261, 0]} />
      </mesh>
      <mesh geometry={nodes.Metal_Bookshelf001.geometry} material={materials['Liquid Metal Material']} position={[20.819, 0.2, -5.862]} rotation={[-Math.PI, 0, -Math.PI]}>
        <mesh geometry={nodes.Metal_bookshelf_Windows001.geometry} material={materials['Windows Material']} position={[0, 0.261, 0]} />
      </mesh>
      <mesh geometry={nodes.Metal_Bookshelf002.geometry} material={materials['Liquid Metal Material']} position={[7.734, 0.2, -17.595]}>
        <mesh geometry={nodes.Metal_bookshelf_Windows002.geometry} material={materials['Windows Material']} position={[0, 0.261, 0]} />
      </mesh>
      <mesh geometry={nodes.Metal_Bookshelf003.geometry} material={materials['Liquid Metal Material']} position={[-10.482, 0.2, 3.264]} rotation={[0, -1.571, 0]}>
        <mesh geometry={nodes.Metal_bookshelf_Windows003.geometry} material={materials['Windows Material']} position={[0, 0.261, 0]} />
      </mesh>
    </group>
  )
}

useGLTF.preload('/Building_1.glb')
